// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('Verifier');

contract('SquareVerifier', accounts => {
    const account1Address = accounts[0];
    const zProof = require("./proof.json");

    beforeEach(async function () {
        this.contract = await SquareVerifier.new({ from: account1Address });
    });

    it('Test verification with correct proof', async function () {
        const { proof: { a, b, c }, inputs: inputs } = zProof;

        let result = await this.contract.verifyTx.call(a, b, c, inputs);

        assert.equal(result, true, "proof_incorrect");
    });

    it('Test verification with incorrect proof', async function () {
        const { proof: { a, b, c } } = zProof;

        let result = await this.contract.verifyTx.call(a, b, c, [0, 0]);

        assert.equal(result, false, "proof_should_not_be_correct");
    });
})